# Generated by Django 4.0.1 on 2023-07-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinalplant',
            name='image',
            field=models.ImageField(upload_to='./static/medicinal_plant_images/'),
        ),
    ]
