# Generated by Django 4.0.1 on 2023-07-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0003_alter_medicinalplant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinalplant',
            name='image',
            field=models.ImageField(upload_to='luomedicine_app/static/medicinal_plant_images/'),
        ),
    ]
