# Generated by Django 4.0.1 on 2023-07-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0004_alter_medicinalplant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinalplant',
            old_name='description',
            new_name='treatment',
        ),
    ]
