# Generated by Django 4.0.1 on 2023-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0006_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinalplant',
            name='part',
            field=models.TextField(default=False),
        ),
    ]
