# Generated by Django 4.2.2 on 2023-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0008_alter_medicinalplant_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuoFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='luomedicine_app/static/luo_foods/')),
            ],
        ),
    ]
