# Generated by Django 4.2.2 on 2023-07-24 13:34

from django.db import migrations, models
import luomedicine_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0009_luofoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luofoods',
            name='image',
            field=models.ImageField(upload_to='luomedicine_app/static/luo_foods/', validators=[luomedicine_app.models.LuoFoods.validate_image_file_extension]),
        ),
    ]
