# Generated by Django 4.2.2 on 2023-07-24 13:38

from django.db import migrations, models
import luomedicine_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('luomedicine_app', '0010_alter_luofoods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinalplant',
            name='image',
            field=models.ImageField(upload_to='luomedicine_app/static/medicinal_plant_images/', validators=[luomedicine_app.models.MedicinalPlant.validate_image_file_extension]),
        ),
    ]
